// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrxiCax2EzeOXojG5RyLLPBjTeu9V2wI',
    appId: '1:807617071655:web:cee8a35aef5c55f0f35c02',
    messagingSenderId: '807617071655',
    projectId: 'education-app-fc4bd',
    authDomain: 'education-app-fc4bd.firebaseapp.com',
    storageBucket: 'education-app-fc4bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VKCTu1HNdH5cnSOFbOiTPRNdBwHOucY',
    appId: '1:807617071655:android:ab86d81d6966900ef35c02',
    messagingSenderId: '807617071655',
    projectId: 'education-app-fc4bd',
    storageBucket: 'education-app-fc4bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkO4QrDqdLPeIzO0UMK2Rp8bFJ7EQcBQs',
    appId: '1:807617071655:ios:a46f514f4f704588f35c02',
    messagingSenderId: '807617071655',
    projectId: 'education-app-fc4bd',
    storageBucket: 'education-app-fc4bd.appspot.com',
    androidClientId: '807617071655-227uore57tga2s74i6n2ju3u7tn1u4mk.apps.googleusercontent.com',
    iosClientId: '807617071655-t2i1vu1h9867om8r4sag0lihgroa97af.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );
}
